extends: default

ignore: |
  charts/llama-8b/templates/
  images/*.svg
  .github/
  dashboards/
  evals/script-configmap.yaml

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  comments-indentation: disable
  indentation:
    spaces: consistent
    indent-sequences: consistent
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  commas:
    max-spaces-after: -1
  colons:
    max-spaces-after: -1
  empty-lines:
    max: 2
