driver:
  enabled: false
toolkit:
  enabled: false
cdi:
  enabled: false
devicePlugin:
  env:
    - name: DEVICE_LIST_STRATEGY
      value: volume-mounts
dcgmExporter:
  enabled: true
  repository: nvcr.io/nvidia/k8s
  image: dcgm-exporter
  version: 3.3.9-3.6.1-ubuntu22.04
  imagePullPolicy: IfNotPresent
  serviceMonitor:
    enabled: true
    interval: 15s
    honorLabels: false
