driver:
  enabled: false
toolkit:
  enabled: false
cdi:
  enabled: false
devicePlugin:
  env:
    - name: DEVICE_LIST_STRATEGY
      value: volume-mounts
dcgmExporter:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
    honorLabels: false
