{{- if .Values.persistence.hfCache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llama.fullname" . }}-hf-cache
  labels: {{- include "llama.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.hfCache.accessMode }}
  storageClassName: {{ .Values.persistence.hfCache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.hfCache.size }}
{{- end }}
