{{- if .Values.hfToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llama.hfSecretName" . }}
  labels: {{- include "llama.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.hfToken.value | quote }}
{{- end }}
