apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-extension-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api-inference-extension.git
    targetRevision: v1.5.0
    path: config/crd/bases
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
