apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    chart: kgateway
    targetRevision: v2.0.4
    helm:
      releaseName: kgateway
      values: |
        inferenceExtension:
          enabled: false
        gatewayClass:
          name: kgateway
        controller:
          replicaCount: 1
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {memory: 512Mi}
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
