apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.3.1
    helm:
      releaseName: kps
      values: |
        crds:
          enabled: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            enableRemoteWriteReceiver: true
            enableFeatures:
              - remote-write-receiver
              - exemplar-storage
            retention: 6h
            enableAdminAPI: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
        alertmanager:
          enabled: true
          alertmanagerSpec:
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
        grafana:
          adminPassword: admin
          service:
            type: ClusterIP
          defaultDashboardsEnabled: true
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
            datasources:
              enabled: true
              searchNamespace: ALL
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  uid: prometheus
                  access: proxy
                  url: http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                  isDefault: true
                  jsonData:
                    exemplarTraceIdDestinations:
                      - name: trace_id
                        datasourceUid: tempo
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki
              access: proxy
              url: http://loki-gateway.monitoring.svc.cluster.local
              jsonData:
                maxLines: 1000
                derivedFields:
                  - name: trace_id
                    matcherRegex: '"trace_id":"(\w+)"'
                    url: '${__value.raw}'
                    datasourceUid: tempo
            - name: Tempo
              type: tempo
              uid: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3100
              jsonData:
                serviceMap:
                  datasourceUid: prometheus
                tracesToLogsV2:
                  datasourceUid: loki
                  filterByTraceID: true
                  tags:
                    - key: service.name
                      value: service
                tracesToMetrics:
                  datasourceUid: prometheus
                  tags:
                    - key: service.name
                      value: service
        kubeStateMetrics:
          enabled: true
        nodeExporter:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
