apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: llama-8b
  namespace: llama
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-8b
      app.kubernetes.io/instance: llama
  targetPortNumber: 8000
  endpointPickerRef:
    name: llama-8b-epp
