apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vllm-api-key
  namespace: llama
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: ClusterSecretStore
  target:
    name: vllm-api-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: vllm
        property: apiKey
